### ISSUE TITLE
Possibly switch from camptocamp-archive to puppet-community/puppet-archive

### ISSUE THREAD

**Issue by antaflos** [lesaux/puppet-kibana4#21]
The `archive` type from https://github.com/puppet-community/puppet-archive is implemented as a native type with multiple providers and has fewer open issues than camptocamp-archive. It also is under the umbrella of the Puppet Community organisation which _should_ mean that issues and PRs are processed quicker; camptocamp-archive has uncommented issues and open PRs dating back one and a half years.

Is there a specific reason you chose camptocamp-archive over puppet-community/puppet-archive (back then it was probably called nanliu/archive)? Would you be open to switch? Or maybe we should let the users decide which `archive` type to use, depending on which module they have deployed in their infrastructure?

**Comment by levenaux** [comment]
+1

**Comment by jordzn** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by madAndroid** [comment]
I'd wholeheartedly agree .. this was previously mentioned in #7

**Comment by lesaux** [comment]
Ok I will look into this.
this module is called "nanliu-archive" on the forge right?

**Comment by lesaux** [comment]
For now I can mostly see cons:

1)In the case of a masterless puppet, the faraday download provider requires to "include '::archive'" so that the faraday gems are installed. I can see work has been done to use wget and curl as download providers, https://github.com/puppet-community/puppet-archive/pull/61 but I don't understand how to enable them as the download providers yet!!
I really don't think I should be "including" another module.
2)nanliu/archive doesn't seem to support using a proxy (#8) so we'd have to remove this feature. (configuring a proxy should probably be taken care of by a specific module anyways)

I'm not sure where I stand and may need more convincing! It would help if version 0.4.0 of nanliu/archive was released.

**Comment by antaflos** [comment]
Those sound like valid reasons. A release _should_ be forthcoming, but who knows.

In any case I think it is probably best to support both `archive` types here and let the user decide which one to use. Not sure how to model that in metadata.json, though. I don't think it supports specifying a dependency on either camptocamp/archive _or_ nanliu/archive.

I'll see if I can put together a PR sometime this week or weekend.

**Comment by antaflos** [comment]
That was faster than expected. I have create PR #23, please have a look.

**Comment by lesaux** [comment]
That PR #23 is pretty good. People that want to use puppet-community/archive will probably be using r10k to manage their dependencies anyways (and not "puppet module install"), so it looks good to me.
I'm not sure how we could write some tests for this though! I'll merge now.
I'd be ok to only support nanliu/archive as soon as it supports wget and/or curl as "downloaders".

**Comment by igalic** [comment]
i'll see to getting puppet-community/archive released asap.

**Comment by walterheck** [comment]
@igalic how's that release coming? Would make things a lot easier for us wanting to use that module :)

**Comment by igalic** [comment]
@walterheck currently struggling with travis: https://github.com/maestrodev/puppet-blacksmith/issues/23

**Comment by igalic** [comment]
puppet community's archive is now released in version 0.4.x!

**Comment by lesaux** [comment]
I've deprecated the `archive` `install_method`.

**Comment by madAndroid** [comment]
> I've deprecated the archive install_method.

Awesome :) since the archive method is no longer available, could you please remove the dependency on `camptocamp/archive` in the `metadata.json`? I'm currently still using a fork of this module due to this being in place (I've removed it in my fork so that librarian-puppet doesn't mistakenly install `camptocamp/archive` instead of `puppet/archive`)

**Comment by lesaux** [comment]
Thank you sir! I had forgotten to remove it.

**Comment by madAndroid** [comment]
@lesaux - ah, fair enough :) no worries!
