### ISSUE TITLE
Consider using puppet-community archive module

### ISSUE THREAD

**Issue by madAndroid** [lesaux/puppet-kibana4#7]
I've come up against an issue where another module in my stack is using the [puppet-community/archive](https://github.com/puppet-community/puppet-archive) module, and this clashes with the camp-to-camp module. Is there any specific reason that the camp-to-camp module was chosen over the puppet-community one?

**Comment by lesaux** [comment]
Hello, thanks for your feeedback.

When I first created this module, I chose the "archive" module with the most downloads on the puppet forge. Since the existence of this module, there already have been two occurrences of camptocamp/archive being broken for a few days - which confused several kibana4 users.

In fact ultimately I would like to get rid of this dependency altogether, and just run a few "execs" to deal with fetching and extracting files myself. Properly done, it would be possible to avoid conflicts with any other modules.

**Comment by madAndroid** [comment]
Hi, thanks for getting back to me, and apologies for the very delayed response ...

We discovered late on Friday that there appears to be a set of packages for Kibana4 in the official elastic.co repos, although there's not been an announcement to this effect just yet.

Related to: https://github.com/elastic/kibana/pull/3212

Is it likely that you'll switch to using the official packages for installation? If so, I'd like to try my hand at a PR to bring this functionality into the module :)

**Comment by madAndroid** [comment]
This is no longer required; in my own install, I've taken to using `camptocamp/archive` as well, but recent changes to allow using system packages should do away with this dependency for me.
